### PR TITLE
BH-1142: Prepare 0.4.2 for release

### PR DESCRIPTION
**Pull request by nickcernis**
- Preps 0.4.2 for release from the `main` branch.
- Excludes taxonomy and relationships features.
- I was unable to find issues under WordPress 5.8, so I bumped "Tested up to" to 5.8 as suggested by @ChrisWiegman.

https://wpengine.atlassian.net/browse/bh-1142

## Testing

Grab the [zip file artifact](https://app.circleci.com/pipelines/github/wpengine/atlas-content-modeler/1359/workflows/7527d0a3-6e37-4a48-826b-34be089c9db3/jobs/11490/artifacts) from Circle once built, and confirm all is well locally.

The PHP unit test failure for `PostTypeRegistrationTestCases::test_graphql_query_result_has_custom_fields_data` is being discussed in Slack. I filed a separate PR in https://github.com/wpengine/atlas-content-modeler/pull/212.

## Screenshots

n/a

## Documentation Changes

n/a

## Dependant PRs

- https://github.com/wpengine/atlas-content-modeler/pull/212 should be merged to main before this is released to prevent CI failures during deployment.

### CODE REVIEW

**Review by ChrisWiegman — DISMISSED** [review]

**Review by mindctrl — DISMISSED** [review]

**Comment by nickcernis** [comment]
Waiting for merge of https://github.com/wpengine/atlas-content-modeler/pull/213.

I'll then update the changelog with that fix and the one from https://github.com/wpengine/atlas-content-modeler/pull/202 that's now in main.

**Comment by nickcernis** [comment]
Updated with latest from main, plus mention of the number field fixes.

**Review by mindctrl — DISMISSED** [review]

**Comment by mindctrl** [comment]
We need to update the change log to include the work in #214.

**Comment by nickcernis** [comment]
Ready for re-review. Updated with mention of the changes in #214.

**Review by mindctrl — APPROVED** [review]

**Review by ChrisWiegman — APPROVED** [review]

**Pull request merged**
