### PR TITLE
Deps: Update word-wrap (via optionator)

### PR DESCRIPTION
**Pull request by theodesp**
## Description

Set optionator overrides to v0.9.3 which fixes word-wrap vulnerability.

https://wpengine.atlassian.net/browse/

https://wpengine.atlassian.net/browse/MERL-1067

## Checklist

I have:

- [ ] Added an entry to CHANGELOG.md.

### CODE REVIEW

**Review by mindctrl — DISMISSED** [review]
LGTM. We can merge after e2e tests pass.

**Comment by mindctrl** [comment]
@theodesp I resolved the merge conflict

**Comment by theodesp** [comment]
I tried to re-install again and i get those errors:

Screenshot 2023-07-11 at 12 37 09

React v16 seems to have a conflict with react-test-renderer@17.0.2

I think React needs to match the version of `react-test-renderer`

**Comment by theodesp** [comment]
Closed since there is a provided fix:

https://github.com/wpengine/atlas-content-modeler/pull/664

**Pull request closed without merging**
