### PR TITLE
[BH-1222]: Add relationship modal empty state and “create entry” link

### PR DESCRIPTION
**Pull request by nickcernis**
Improves the empty state of the relationships modal table:

- Removes the pagination if there are zero pages. (Previously, “Page 1 of 0” would appear if there were no entries.)
- Displays an empty message if there are no entries. 
- Adds a link in the modal to create a new entry if there are no entries. Clicking the link closes the modal and opens the “New [Singular]` page in a new tab. This removes a potential dead end, where the user would have to figure out how to create a related entry themselves and then refresh the original page to see those new entries (potentially losing unsaved work in the process).

## Testing

Includes an e2e test for the “create new entry” flow.

### To test manually

1. Create a “Monkey” model with a “name” text field set as the title, and a “Monkey Friends” relationship field that refers to other monkeys.
2. Add your first monkey.
3. Click the relationship field to open the relationship modal. You should see no entries. Click the link named, “Create a new Monkey”.
4. In the new tab that opens, create a new monkey by just filling its name, then publish it.
5. Close the tab to return to the original monkey entry.
6. The relationship modal should update to show the monkey you entered.

## Screenshots

| Before | After |
| - | - |
| Screenshot 2021-08-31 at 13 29 10 | Screenshot 2021-08-31 at 13 28 42 |

### CODE REVIEW

**Review by mindctrl — APPROVED** [review]

**Comment by nickcernis** [comment]
Current plan for this is to:

1. Update the “Create a new [Entry]” link with an “opens in new tab” icon and aria-label. (Awaiting icon from Mason.)
2. Change modal behaviour to stay open when the new tab opens, then re-fetch entries when focus returns to the tab.

I can make time to work on these once we have the icon.

**Comment by nickcernis** [comment]
This is ready for another look.

- The link now includes an icon to show that it opens in a new window/tab.
- Added aria-label with appended “Opens in a new window” text.
- The modal stays open and refreshes when someone returns to the tab (tested Chrome, Firefox, Safari).

https://user-images.githubusercontent.com/647669/131733149-4d77929d-a5c1-4cee-bb6e-0490a339ac5a.mp4

Screenshot 2021-09-01 at 21 29 03

**Review by mindctrl — APPROVED** [review]
Works great!

**Review by ChrisWiegman — APPROVED** [review]
This seems to be working for me. Thank you! LGTM!

**Pull request merged**
